### ISSUE TITLE
crontab.bat里面的路径写死了

### ISSUE THREAD

**Issue by francis-xjl** [qiu8310/crontab#1]
crontab.bat里面的路径写死了

**Comment by francis-xjl** [comment]
忽略吧， 没注意到安装步骤里已经说明了。

**Comment by qiu8310** [comment]
这项目好久没更新了。。。都不知道 window 还用不用的了

**Comment by francis-xjl** [comment]
我觉得挺好的，我在用~要是没有这个项目，我都准备用python重新写一个了，我用来给我的博客定时备份到笔记本上。我安装成功了，不过有个点：

我机器上nircmd.exe在执行计划中执行有些问题，不太清楚具体是什么原因。不过，其实要想隐藏java命令出现的黑框，直接用javaw替换即可，因此我在安装服务之前，把crontab_intall.bat里的内容做了修改，把nircmd替换成了javaw，如下所示：

schtasks /create /tn "MyCrontabTask" /tr "javaw -cp E:\Development\runtimes\crontab-win\bin com.main.Crontab -r" /sc MINUTE /mo 1

**Comment by qiu8310** [comment]
学习了！

我也是好久没写 java 了~
